macadmins/sofa

.github/workflows/run_docker_workflow.yml

Update run_docker interval

---

build-sofa-feed.py
dockerfile
process_uma.py

adds trailing 'InstallationApps' stanza with UMA info (latest and all currently published) & links
tested in Docker

initial process_uma checkin

---

build-sofa-feed.py

 Introduce more Doc String Sections and Clean Up unused functions

---

build-sofa-feed.py
index.html

This PR adds UMA info from the feed to the UI.
Also small enhancements made, e.g. incorporate the fire emoji for actively exploited CVEs

Add UI refinements, UMA info download,  

---

LICENSE

including a license file for the use and contributions

Create LICENSE - Apache 2.0

---

README.md

This is the first version of the docs in the ReadMe

Add initial ReadMe

---

tool-scripts/XProtectVersionCheck-EA.sh
tool-scripts/macOSVersionCheck-EA.sh
tool-scripts/swift_dialog.sh

- Adds macOSVersionCheck.sh
- Updates XProtectVersionCheck.sh to use plutil (mainly to align with macOSVersionCheck.sh)
- Update URL in swiftdialog.sh to macadmins

New EA for SU check

---

index.html

slight rename of vars and text in index.html

Make Xprotact names more distinct in web UI

---

index.html

Add simple description when UrL posted in social feeds.

add meta tag infro to index.html

---

build-sofa-feed.py

Use a simpler JSON value in `Models` > `SupportedOS`.

Align formatting for value  in  Models > SupportedOS

---

tool-scripts/macOSVersionCheck-EA.sh

Very minor update to reflect changes to the `SupportedOS` values.

Sed no longer needed

---

index.html

While I was checking out this cool project (great job btw!), curiosity got me to look at how the UI was built. Reading over the code, I noticed some misalignment. Just submitted a PR to align it.
I also noticed (after fixing this) that @grahampugh linter most likely caught it in #60 . Mine caught a bunch of stuff but wanted to keep this PR small without major modifications. You can close if #60 is landed. Figured you can have choices. 😄 
Tested locally by running a python web server on the directory as well as console errors within the developer tools.
```bash
➜  sofa git:(main) ✗ sudo python3 -m http.server 80
Serving HTTP on 0.0.0.0 port 80 (http://0.0.0.0:80/) ...
127.0.0.1 - - [29/Apr/2024 16:34:43] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [29/Apr/2024 16:36:36] "GET / HTTP/1.1" 304 - …
```

Fix JS misalignment within HTML

---

build-sofa-feed.py
dockerfile
process_ipsw.py

Closes #67, all thanks to @ninxsoft, this is low-hanging fruit to at least get one ipsw for macs available.
As usual, more data in the feed than we expect in the GUI

add initial macOS ipsw parse

---

tool-scripts/XProtectVersionCheck-EA.sh
tool-scripts/macOSCVECheck-EA.sh
tool-scripts/macOSCompatibilityCheck-EA.sh
tool-scripts/macOSVersionCheck-EA.sh

Hi there, the sysctl tool provides a much simpler and more reliable way of retrieving the device model.

Use sysctl to identify device model

---

model_identifier_sequoia.json

add initial sequoia model info

---

model_identifier_ventura.json

correct MacBookAir for Ventura

---

build-sofa-feed.py
dockerfile

240629 cache gdmf

---

.flake8
.pre-commit-config.yaml
build-sofa-feed.py
process_ipsw.py
process_uma.py
ruff.toml

while reviewing, reordered all functions sequentially and cut down on whitespace. Added precommit w/isort, blackened/ruff formatted, basic flake8'd, ruff check'd with flake suggested codes, mypy type checked and corrected everything it mentioned. Mid-pylinting for warnings (rates a 9.11), TODO's scattered, but a start
Please note all pre-commit checks are optional unless you local install the hooks, open to removing anything we don't want to standardize and I admit there's a lot of overlap in the checks, but they're only minimally muted

post initial code review, lint/style/type checking

---

.github/workflows/fetch_cve_details.yml
build-cve-cache.py

add cve cache

---

build-cve-cache.py

when caching NVD++ data from vulncheck

add correct user-agent

---

.github/workflows/run_docker_macos_workflow.yml

When running vitepress locally, this allowed me to access the file as expected: 
```
http://localhost:5173/v1/macos_data_feed.json
```

Update workflow to place json in public folder for vitepress

---

cache/cve_details.json
web/.vitepress/config.mts

Currently, when the SOFA web URL is unfurled by Slack and other tools, the provided description and title are very minimal and don't provide much context:
This pull request adds some context by spelling out MAOS and providing a more detailed description of what SOFA is.

Update HTML title and description

---

.github/workflows/fetch_cve_details.yml
.github/workflows/run_docker_macos_workflow.yml

Add rss_feed.xml back to sofafeed.macadmins.io

---

web/components/CveSearch.vue
web/components/SecurityInfo.vue
web/cve-search.md

240814 UI improvments for CVE Search and Security info 

---

build-sofa-feed.py

```
Updated 14.6.1 ReleaseDate from 2024-08-14T00:00:00Z to 2024-08-07T00:00:00Z
Updated 13.6.9 ReleaseDate from 2024-08-14T00:00:00Z to 2024-08-07T00:00:00Z
Updated 12.7.6 ReleaseDate from 2024-08-14T00:00:00Z to 2024-07-29T00:00:00Z
```
fixes https://github.com/macadmins/sofa/issues/97
tl/dr
- during the original loop, gather all the release dates in a dictionary
- added a second loop to compare all of the release dates against all of the Latest, compare against ProductVersion - if there is a match, replace it.

fix latest release dates to match security dates

---

web/self-hosted.md

240817 self hosted docs

---

web/self-hosted.md

Fix remaining glitch in example

Add correct config description.

---

cache/macOS_beta_info.json

Update missing beta info for macOS Sequoia

Add updated Sequioa info

---

cache/macOS_beta_info.json
web/components/SecurityInfo.vue

This PR improve CVEs to ordered better, starting with the highest year first

240831 improved CVE order

---

config.json
web/.vitepress/config.mts
web/iOS_18.md
web/index.md
web/macOS_Monterey.md
web/macOS_Sequoia.md
web/macOS_Sonoma.md
web/macOS_Ventura.md

Update fetch for new OS version and add info to WebUI info and navigation

240916 new os released

---

build-sofa-feed.py

Addresses https://github.com/macadmins/sofa/issues/180 and https://github.com/macadmins/nudge/issues/655

return empty keys if we dont have any data

---

web/.vitepress/config.mts
web/components/ReleaseInstallerTable.vue
web/macos_installer_info.md

Add links to IPSW and UMA files and restore ability to quickly download latest versions

Add section for UMA and PKG download links

---

build-sofa-feed.py

Fix issue with DaysSincePreviousRelease calculation

---

build-sofa-feed.py

Since the release of macOS 15, there have been changes to the `.sucatalog` that include multiple `XProtectPlistConfigData .pkm` files. These files are now sorted by date, allowing to gather the latest version of XProtect information.

Fix: Update XProtect info from latest catalog

---

web/components/LatestFeatures.vue

Add feature with OS deferral thresholds to Last OS Info

Add table with deferrals

---

cache/essential_links.json

Add new link for `AppleSeed for IT` to Essential Apple Resources

Add new link AppleSeed for IT

---

web/.vitepress/config.mts
web/components/ReleaseDeferralTable.vue
web/release-deferrals.md

Quickly inspect OS deferrals across the major OS versions

Add sub page with OS deferral overview

---

web/components/CveDetails.vue
web/components/CveSearch.vue

enhance CVE search features and provide link to cvefeed.io

241023 CVE link details

---

cache/model_identifier_sequoia.json

Add Model Identifier info as released by Apple here:
- https://support.apple.com/en-ca/108052
- https://support.apple.com/en-ca/102852
- https://support.apple.com/en-ca/108054

Add the new Hardware released for Sequoia

---

cache/model_identifier_sequoia.json
cache/model_identifier_sonoma.json

241109 new mac models

---

web/components/ReleaseDeferralTable.vue

ensure we present more recent versions and display them

---

web/.vitepress/config.mts
web/iOS_26.md
web/index.md
web/macOS_Sonoma.md
web/macOS_Tahoe.md

Update web resources for Tahoe and iOS 26

Add Tahoe and iOS 26 pages

---

web/components/LatestFeatures.vue

Add new icons to the component

Add icons to the pages

---

web/macos_installer_info.md

Add link to external IPSW source

---

requirements.txt

Remove python requirements file

---

.github/workflows/02_cve-pipeline.yml

We add more historic and valuable files fetched and processed to committed data

Update GH Action to commit more files
