tool-scripts/XProtectVersionCheck-EA.sh, tool-scripts/macOSVersionCheck-EA.sh
Adding `--no-rcs` to the zsh shebang prevents these scripts being a part of the CVE-2024-27301 exploit which can execute lines in `.zshenv` as root.
=> Prevent CVE-2024-27301 exploit of zsh scripts

tool-scripts/XProtectVersionCheck-EA.sh, tool-scripts/macOSCVECheck-EA.sh, tool-scripts/macOSVersionCheck-EA.sh
Added a new EA that shows unpatched CVEs, limited to the major version that the system is running.
The result shows both the number of total CVEs, plus the number of actively exploited CVEs in a way that both can be easily used in a Smart Group criterion.
```
<result>CVEs:149 ActiveExploits:5</result>
```
To use in Smart Groups:
- To check only for Active Exploits:
```
macOS CVE Check - matches regex - ActiveExploits:[1-9]
```
- To check for any CVEs:
```
macOS CVE Check - matches regex - CVEs:[1-9]
```
I also added checks for the system OS in the other two EAs so they gracefully exit if run on a system older than macOS 12.
=> EA to show unpatched CVEs

build-sofa-feed.py
When run via GitHub Action the `-e TIMESTAMP_FILE_PATH=/app/v1/timestamp.json` must be used
=> Fix writing of timestamp file location, respect env variable

v1/v1_mac.schema
nails down v1 for the mac feed, `pip(3) install check-jsonschema` (in the venv of your choice, hopefully dropping it into your path), then `check-jsonschema  --schemafile sofa/v1/v1_mac.schema sofa/v1/macos_data_feed.json` for great rejoicing
if it all worked, you'd see
```
ok -- validation done
```
=> Initial jsonschema checkin

build-sofa-feed.py
This extends the `Latest` to contain all of the relevant data from the Security Releases section
Ex:
```json
"Latest": {
"ProductVersion": "14.5",
"Build": "23F79",
"ReleaseDate": "2024-05-13T00:00:00Z",
"ExpirationDate": "2024-08-15T00:00:00Z",
"SupportedDevices": [
"J132AP",
"J137AP",
"J140AAP",
"J140KAP",
"J152FAP",
"J160AP",
"J174AP",
"J180dAP",
"J185AP",
"J185FAP",
"J213AP",
"J214KAP",
"J215AP",
"J223AP",
"J230KAP",
"J274AP",
"J293AP",
"J313AP",
"J314cAP",
"J314sAP",
"J316cAP",
"J316sAP",
"J375cAP",
"J375dAP",
"J413AP",
"J414cAP",
"J414sAP",
"J415AP",
"J416cAP",
"J416sAP",
"J433AP",
"J434AP",
"J456AP",
"J457AP",
"J473AP",
"J474sAP",
"J475cAP",
"J475dAP",
"J493AP",
"J504AP",
"J514cAP",
"J514mAP",
"J514sAP",
"J516cAP",
"J516mAP",
"J516sAP",
"J613AP",
"J615AP",
"J680AP",
"J780AP", …
```
=> add CVE info to latest release

tool-scripts/XProtectVersionCheck-EA.sh, tool-scripts/macOSCVECheck-EA.sh, tool-scripts/macOSCompatibilityCheck-EA.sh
As discussed in Slack channel - this PR causes the EAs to cache the file locally along with an eTag file, which is used to compare local to online, so the full file is only downloaded when a change is made.
I chose `/private/tmp/sofa` as the cache folder, but this could be altered to something more permanent.
=> use local cached file and do etag checks to prevent unnecessary downloads

build-sofa-feed.py
Not sure how this one passed tests but seems I left double quotes for `ProductName` within the f-string.
=> Fixing quotes issue for ProductName

.github/workflows/run_docker_macos_workflow.yml
Lately we have been seeing 403 client errors in the GDFM feed, this does affect the build of our feed files. 
Temporary reduction of cron activity for better analysis.
=> reduce cron interval

tool-scripts/XProtectVersionCheck-EA.sh, tool-scripts/XProtectVersionCheck-swiftDialog.sh, tool-scripts/macOSCVECheck-EA.sh, tool-scripts/macOSCompatibilityCheck-EA.sh, tool-scripts/macOSVersionCheck-EA.sh
This adds individual user-agent strings to the `curl` requests in each of the EAs so that the requests from the "official" EAs can be seen.
=> Add user agents to the Jamf EA scripts

tool-scripts/XProtectVersionCheck-EA.sh, tool-scripts/XProtectVersionCheck-swiftDialog.sh, tool-scripts/macOSCVECheck-EA.sh, tool-scripts/macOSCompatibilityCheck-EA.sh, tool-scripts/macOSVersionCheck-EA.sh
explicitly add a compressed option to curl requests for demo extension attributes 
this is tested as far back as 10.15.7
curl by default will not add an 'accept-encoding' header, thus all of the json coming back will be uncompressed, but this is highly compressible (over 90% with gzip which is broadly supported)
newer curl versions will use brotli if support is compiled in, but 90% bandwidth savings is probably good enough
=> explicity tell cURL to request compressed data

tool-scripts/GoogleSheet.gs, tool-scripts/ReadMe.md, tool-scripts/XProtectVersionCheck-EA.sh, tool-scripts/XProtectVersionCheck-swiftDialog.sh, tool-scripts/macOSCVECheck-EA.sh, tool-scripts/macOSCompatibilityCheck-EA.sh, tool-scripts/macOSVersionCheck-EA.sh
This updates the URLs to `sofafeed` in all the Extension Attribute scripts plus the Google Sheets and SwiftDialog example scripts.
=> update feed URL in all the tool-scripts

build-sofa-feed.py
Here we remove "pretty print" on our feed file JSON to reduce more bandwidth
=> switch feed output to non-pretty print

web/.vitepress/config.mts
In testing this resulted in static filename "style.css" so we may not see the CSS issues anymore
=> Potential fix for CSS issues seen on rebuild

dockerfile
The `model_identifier_*.json` files reside in the cache folder to be used in the web UI for a while now. 
In our Docker workflow, we should now use the same files to avoid drift.
=> Change docker file to copy model_identifier_*.json from cache now

.github/workflows/fetch_cve_details.yml
Automated runs for the [fetch_cve_details.yml](https://github.com/macadmins/sofa/blob/main/.github/workflows/fetch_cve_details.yml) action did fail few times. 
Set to different schedules might be resolve this, as manual runs have been running fine.
=> Use a different schedule for CVE fetching to avoid collisions.

tool-scripts/XProtectVersionCheck-EA.sh, tool-scripts/XProtectVersionCheck-swiftDialog.sh, tool-scripts/macOSCVECheck-EA.sh, tool-scripts/macOSCompatibilityCheck-EA.sh, tool-scripts/macOSVersionCheck-EA.sh
`curl` will output a 0 byte file to the `--etag-save` path if `--etag-compare` passes. From the `curl` manpage:
```
--etag-compare <file>
(HTTP) This option makes a conditional HTTP request for the
specific ETag read from the given file by sending a custom
If-None-Match header using the stored ETag.
For correct results, make sure that the specified file contains
only a single line with the desired ETag. An empty file is
parsed as an empty ETag.
Use the option --etag-save to first save the ETag from a
response, and then use this option to compare against the saved
ETag in a subsequent request.
```
This causes the scripts to re-download the SOFA json file on every other re-run because the cached etag file (which is also the file being compared) is empty, so curl's `--etag-compare` fails …
=> Fix curl etag handling

build-sofa-feed.py
Needed because since 2024-09-04 Apple now redirects 'old' https://support.apple.com/en-us/HT201222 to 'new' home under "https://support.apple.com/en-us/100100
=> Add: Fix to update URL in fetch_security_releases function

cache/essential_links.json, v1/v1_data_feed.md, v1/v1_mac.schema, web/components/SecurityInfo.vue
Formerly the reference was HT201222 now it's available under "https://support.apple.com/en-us/100100
=> Update references to new URL

build-sofa-feed.py
This PR addresses the issue reported in #174 by appending `.0` to the `product_version` in the feed.
=> Add changes for several issues reported in feed files 

tool-scripts/XProtectVersionCheck-EA.sh, tool-scripts/XProtectVersionCheck-swiftDialog.sh, tool-scripts/macOSCVECheck-EA.sh, tool-scripts/macOSCompatibilityCheck-EA.sh, tool-scripts/macOSVersionCheck-EA.sh, tool-scripts/macOSVersionDisplacement-EA.sh
Changed `/private/tmp` to `/var/tmp` due to issues experienced with the former returning older versions of the file if recently updated (why? no idea) which could cause the OS Compatibility Check to fail.
Also added in a validation check to make sure we have a model name. This wasn't directly an issue but it could potentially be so adding it in for completeness.
Each script has been tested (N=1).
Additionally `macOSCompatibilityCheck-EA.sh` has been tested in a Jamf Pro environment where the issue was first noticed
=> relocate temp files to /var/tmp

tool-scripts/macOSCompatibilityCheck-EA.sh
update the quotations around model when using the python2 method for macOS 11 hosts. This fixes an issue where the model truncates on the comma (e.g. MacBookAir10,1 becomes MacBookAir10) and the lookup will then fail.
Before:
```bash
% python -c 'import sys, json; print json.load(sys.stdin)["Models"]['"$model"']["SupportedOS"][0]' < "$json_cache"
Traceback (most recent call last):
File "<string>", line 1, in <module>
NameError: name 'MacBookAir10' is not defined
```
After:
```bash
% python -c 'import sys, json; print json.load(sys.stdin)["Models"]["'${model}'"]["SupportedOS"][0]' < "$json_cache"
Sequoia 15
```
=> update the quotations around model when using python2 

cache/model_identifier_sonoma.json
Fix for model identifier listing for Sonoma, as reported in #183.
=> Update model info for Sonoma, remove MacBook10,1

build-sofa-feed.py
This is a hot-fix for #201 - works via prioritized larger device counts
`len(version.get("SupportedDevices", [])),`
=> Forked build descending SupportedDevices count order

tool-scripts/macOSMaxVersionCheck-EA.sh
This is similar to existing EAs, but we don't have one that spits out the actual highest major version that is compatible with the client. This is useful for scoping of tools like erase-install and Nudge which may have different settings depending on whether the computer can run the latest macOS or not. 
For example, we've had customers who want to push to 14.7 for any computer that can only go that high, but do not want to push to 15.x for computers that can.
=> new EA to determine the latest compatible macOS

build-sofa-feed.py
When looking at our current CI/CD runs we see this
```
Updated 15.0.1 with SupportedDevices: ['J132AP', 'J137AP', 'J140AAP', 'J140KAP', 'J152FAP', 'J160AP', 'J174AP', 'J180dAP', 'J185AP', 'J185FAP', 'J213AP', 'J214KAP', 'J215AP', 'J223AP', 'J230KAP', 'J274AP', 'J293AP', 'J314cAP', 'J314sAP', 'J316cAP', 'J316sAP', 'J375cAP', 'J375dAP', 'J414cAP', 'J414sAP', 'J415AP', 'J416cAP', 'J416sAP', 'J433AP', 'J434AP', 'J456AP', 'J457AP', 'J473AP', 'J474sAP', 'J475cAP', 'J475dAP', 'J493AP', 'J504AP', 'J514cAP', 'J514mAP', 'J514sAP', 'J516cAP', 'J516mAP', 'J516sAP', 'J613AP', 'J615AP', 'J680AP', 'J780AP', 'Mac-1E7E29AD0135F9BC', 'Mac-63001698E7A34814', 'Mac-937A206F2EE63C01', 'Mac-AA95B1DDAB278B95', 'VMA2MACOSAP', 'VMM-x86_64']
Updated 15.0 with SupportedDevices: ['J132AP', 'J137AP', 'J140AAP', …
```
=> Interrogate all updates and compare with known supported devices

web/use-cases.md
This removes the mention of the old feed. We should still call out using a user agent, etc.
=> Remove mention of old json feeds

cache/supported_devices.json
Fix for #218 Remove incompatible items from the list for macOS 15
J140aAP  == MacBook Air (Retina, 13-inch, 2019)
J140kAP == MacBook Air (Retina, 13-inch, 2018)
=> Remove non comaptible Sequoia devices

cache/model_identifier_sonoma.json
Add Identifiers for new devices, updated according to: https://support.apple.com/en-us/102869 and https://support.apple.com/en-us/102231
=> Add information for MacBook Air and Mac Studio models released in Spring 2025

build-sofa-feed.py, cache/model_identifier_tahoe.json, config.json
- Add model_identifier_tahoe.json to cache folder
- Add tahoe and iOS 26 to config.json
- Reference the model_files model_identifier_tahoe.json in `build-sofa-feed.py`
=> Add Tahoe to v1 feed building 

web/components/LatestFeatures.vue
Fixed UI, as it was avail under macOS 15 but pointing to macOS 26 IPSW. Now IPSW is under Tahoe.
alternative for IPSW downloads of older OS versions cloud be pointing folks to https://appledb.dev/firmware.html
=> Fix link to IPSW
